# Usa una imagen base de Python 3.10 ligera (slim)
FROM python:3.10-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el archivo de requerimientos de Python y los instala
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto de los archivos de la aplicación al contenedor
COPY . .

# Expone el puerto 8000
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python3", "app.py"]
